import type { DashboardWidgetLayout } from "@/lib/types/app";

export const DEFAULT_DASHBOARD_LAYOUT: DashboardWidgetLayout[] = [
  {
    id: "w-receita-hoje",
    type: "kpi-receita-hoje",
    title: "Faturamento de Hoje",
    colSpan: 1,
    rowSpan: 1,
    settings: { limit: 6 },
  },
  {
    id: "w-receita-mes",
    type: "kpi-receita-mes",
    title: "Faturamento do Mes",
    colSpan: 1,
    rowSpan: 1,
    settings: { limit: 6 },
  },
  {
    id: "w-lucro-liquido",
    type: "kpi-lucro-liquido",
    title: "Lucro Liquido",
    colSpan: 1,
    rowSpan: 1,
    settings: { limit: 6 },
  },
  {
    id: "w-ticket-medio",
    type: "kpi-ticket-medio",
    title: "Ticket Medio",
    colSpan: 1,
    rowSpan: 1,
    settings: { limit: 6 },
  },
  {
    id: "w-pagamentos",
    type: "chart-pagamentos",
    title: "Vendas por Forma de Pagamento",
    colSpan: 2,
    rowSpan: 1,
    settings: { limit: 8 },
  },
  {
    id: "w-produtos-vendidos",
    type: "chart-produtos-vendidos",
    title: "Produtos Mais Vendidos",
    colSpan: 2,
    rowSpan: 1,
    settings: { limit: 8 },
  },
  {
    id: "w-despesas-categoria",
    type: "chart-despesas-categoria",
    title: "Despesas por Categoria",
    colSpan: 2,
    rowSpan: 1,
    settings: { limit: 8 },
  },
  {
    id: "w-estoque-critico",
    type: "table-estoque-critico",
    title: "Estoque Critico",
    colSpan: 1,
    rowSpan: 1,
    settings: { limit: 6 },
  },
  {
    id: "w-produtos-lucrativos",
    type: "table-produtos-lucrativos",
    title: "Produtos Mais Lucrativos",
    colSpan: 1,
    rowSpan: 1,
    settings: { limit: 6 },
  },
];
